/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodepolimorfisme;

import java.io.File;
import javax.sound.midi.Instrument;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author Rifki
 */
public class PolymorphicArgumentsGUI extends javax.swing.JFrame {

    /**
     * Creates new form PolymorphicArgumentsGUI
     */
    public abstract class AlatMusik {
        public abstract void mainkan();  // Metode abstrak untuk dimainkan
    }

    // Kelas turunan Gitar
    public class Gitar extends AlatMusik {
        @Override
        public void mainkan() {
            System.out.println("Memainkan suara Gitar");
            // Kode untuk memutar suara gitar bisa ditambahkan di sini
        }
        
        public String getFilePath() {
            return "C:\\gitar.wav";  // Ganti dengan path yang sesuai
        }
    }

    // Kelas turunan Piano
    public class Piano extends AlatMusik {
        @Override
        public void mainkan() {
            System.out.println("Memainkan suara Piano");
            // Kode untuk memutar suara piano bisa ditambahkan di sini
        }
        
        public String getFilePath() {
            return "C:\\piano.wav";  // Ganti dengan path yang sesuai
        }
    }

    // Kelas turunan Drum
    public class Drum extends AlatMusik {
        @Override
        public void mainkan() {
            System.out.println("Memainkan suara Drum");
            // Kode untuk memutar suara drum bisa ditambahkan di sini
        }
        
        public String getFilePath() {
            return "C:\\drum.wav";  // Ganti dengan path yang sesuai
        }

    }

    public PolymorphicArgumentsGUI() {
        initComponents();
    }
    
    private void mainkanAlatMusik(AlatMusik alatMusik) {
        alatMusik.mainkan(); // Polymorphic call
    }
    
    private void playSound(String filePath) {
        try {
            File file = new File(filePath);
            if (!file.exists()) {
                JOptionPane.showMessageDialog(this, "File musik tidak ditemukan: " + file.getAbsolutePath());
                return;
            }

            AudioInputStream audioStream = AudioSystem.getAudioInputStream(file);
            Clip clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start();

            while (!clip.isRunning()) {
                Thread.sleep(10);
            }

            while (clip.isRunning()) {
                Thread.sleep(10);
            }

            clip.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memutar suara: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alat Musik");

        jLabel2.setText("Pilih Alat Musik");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gitar", "Piano", "Drum" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mainkan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(jButton2)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(jButton2)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String pilihan = (String) jComboBox1.getSelectedItem();
        AlatMusik alatMusik = null;

        // Cek pilihan yang dipilih
        if (pilihan == null) {
            JOptionPane.showMessageDialog(this, "Pilih alat musik terlebih dahulu.");
            return;
        }

        // Tentukan objek alat musik berdasarkan pilihan
        switch (pilihan) {
            case "Gitar":
                alatMusik = new Gitar();  // Polymorphic instance
                break;
            case "Piano":
                alatMusik = new Piano();  // Polymorphic instance
                break;
            case "Drum":
                alatMusik = new Drum();   // Polymorphic instance
                break;
            default:
                JOptionPane.showMessageDialog(this, "Alat musik tidak dikenal.");
                return;
        }

        // Memastikan objek alatMusik sudah dibuat
        if (alatMusik != null) {
            alatMusik.mainkan();  // Memanggil metode mainkan menggunakan polymorphism
        }// TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolymorphicArgumentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolymorphicArgumentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolymorphicArgumentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolymorphicArgumentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverLoadingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
